name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository # This step has 'uses'
        uses: actions/checkout@v4

      - name: Set up Python # This step has 'uses'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies for linting # This step has 'run'
        run: |
          python -m pip install --upgrade pip
          pip install flake8 yamllint

      - name: Lint Python files # This step has 'run'
        run: |
          flake8 app/app.py app/requirements.txt # Adjust paths if needed
        continue-on-error: true # This is a property of the 'step'

      - name: Lint YAML files # This step has 'run'
        run: |
          yamllint docker-compose.yml nginx/nginx.conf .github/workflows/ci-cd.yml
        continue-on-error: true

  build-docker-images:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository # This step has 'uses'
        uses: actions/checkout@v4

      # - name: Log in to Docker Hub (optional, if pushing to registry) # This is commented out.
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Compose services # This step has 'run'
        run: docker compose build --no-push

      - name: Verify built images (optional) # This step has 'run'
        run: |
          docker images