---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies for linting
        run: |
          python -m pip install --upgrade pip
          pip install flake8 yamllint

      - name: Lint Python files
        run: |
          flake8 app/app.py
        continue-on-error: true

      - name: Lint YAML files
        run: |
          yamllint docker-compose.yml  # Removed .github/workflows/ci-cd.yml
        continue-on-error: true

  build-docker-images:
        runs-on: ubuntu-latest
        needs: lint # This job depends on the 'lint' job completing
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }} # Use a PAT for password

          - name: Build Docker Compose services
            run: |
              # Build the specific 'web_app' service image
              docker compose build web_app
              # Tag the image with your Docker Hub username/repo:tag
              # Replace 'your-dockerhub-username' with your actual Docker Hub username
              # Replace 'realistic-infra-app' with your desired image name on Docker Hub
              docker tag realistic-infra-project-web_app:latest muhiuddin/realistic-infra-app:latest
              # Or, for versioning, use a commit SHA or a semantic version:
              # docker tag flask_app your-dockerhub-username/realistic-infra-app:${{ github.sha }}

          - name: Push Docker image to Docker Hub
            run: |
              # Push the tagged image
              docker push muhiuddin/realistic-infra-app:latest
              # If you used commit SHA for tagging:
              # docker push your-dockerhub-username/realistic-infra-app:${{ github.sha }}

          - name: Verify built images (optional - runs locally in runner)
            run: |
              docker images # This lists images on the runner, not pushed ones